#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
# if you want to include ruby gems sources in your tags file
# add 'bundle show --paths;' right before 'git ls-files'
ctags -f"$dir/$$.tags" --recurse `git ls-files` --tag-relative --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
